crawler:
  max_depth: 1
  delay_between_requests: 1.0
  max_pages_per_domain: 10
  user_agent: "CustomWebCrawler/1.0"
  ignored_extensions:
    - .pdf
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .css
    - .js
    - .ico
    - .xml
    - .svg

openai:
  model: "gpt-3.5-turbo-1106"
  temperature: 0.7
  max_tokens: 500

vector_store:
  chunk_size: 100
  chunk_overlap: 50

logging:
  level: INFO
  file: "crawler.log"